### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by capinemo** [capinemo/LandScape2.5D#3]
LandScope2.5D Editor 
- [ ] Rendering with SVG
- [ ] Interface with parameters for Generator
- [ ] Interface for saving map object
- [ ] Saving in file, MySQL, PostgreSQL
- [ ] Saving in file, MySQL, PostgreSQL
- [ ] Creating areas with defined background images, setting climatic options depending position above sea level
- [ ] Setting side lighting
- [ ] Moving, rising/deeping points and cells
- [ ] Rotate map with recalculations points coordinates and redraw cells (with lighting)
- [ ] Save small map images as background of global map cells
