### ISSUE TITLE
TODO Viewer

### ISSUE THREAD

**Issue by capinemo** [capinemo/LandScape2.5D#4]
- [ ] Rendering with 2d context
- [ ] Rendering with webGL context
- [ ] Caching map regions
- [ ] Loading from variable
- [ ] Loading from MySQL
- [ ] Loading from PostgreSQL
- [ ] Loading from map-file
- [ ] Saving last view position coordinates in localStorage or Cookies
- [ ] Rendering with SVG
- [ ] Loading path of map to views on display + delta for moving map with mouse
- [ ] Interface for moving with coordinates of cells
- [ ] Clearing buffer with cells hidden after mouse moving
- [ ] Minimap interface
