### ISSUE TITLE
TODO Generator

### ISSUE THREAD

**Issue by capinemo** [capinemo/LandScape2.5D#5]
- [X] Generating map matrix with cells and points. Maximum size 1000x1000, temporary
- [X] Set points position with and without deviation on X and Y in range -20%:20% from cells length
- [ ] Set points position with deviation on Z in range from Vertical minimum input to Vertical maximum input. Points Z position less than Sea level is under water
- [ ] Generating different types of terrain: continent, island, archipelago, lakes and coast
- [ ] By the way, difference between the nearby points on Z must have not more than 1 level.
- [ ] Generating small maps as parts of global map. Maximum size of small map is 128x128 and it is equal to 1 cell of global map.
- [ ] In generation process Generator must send path of data to Editor with saving the information about sent data and clearing of the cache
- [X] Generator must send generation progress values
